steps:
  - name: cypress/included:4.4.0
    entrypoint: npm
    args: ['ci']
  - name: cypress/included:4.4.0
    entrypoint: npm
    args: ['run', 'lint']
  - name: cypress/included:4.4.0
    entrypoint: npm
    args: ['test']
  - name: cypress/included:4.4.0
    entrypoint: npm
    args: ['run', 'e2e']
artifacts:
  objects:
    location: 'gs://eu.artifacts.sme-self-eval-tool-99p47-dev.appspot.com/artifacts'
    paths: [
      '/workspace/cypress/screenshots/**.*',
      '/workspace/cypress/videos/**.*',
      '/builder/home/.npm/_logs/**.log'
    ]
timeout: '1600s'
