steps:
- name: node:10.19.0
  entrypoint: npm
  args: ['ci']
- name: node:10.19.0
  entrypoint: npm
  args: ['run', 'build'],
  env:
  - 'API_HOST=https://api-dot-sme-self-eval-tool-99p47-dev.appspot.com'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
timeout: "1600s"
